name: validate article
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  validate-articles:
    # Only run if it's not a comment trigger, or if it's a retest comment on a PR
    if: |
      github.event_name != 'issue_comment' ||
      (github.event.issue.pull_request && contains(github.event.comment.body, 'retest'))
    uses: Adobe-Enterprise-Docs/workflows/.github/workflows/validate-articles.yml@main
    with:
      debug: true
    secrets:
      SCCM_GITHUB_APP_ID: ${{ secrets.SCCM_GITHUB_APP_ID }}
      SCCM_GITHUB_APP_PRIVATE_KEY: ${{ secrets.SCCM_GITHUB_APP_PRIVATE_KEY }}
      SCCM_SLACK_TOKEN: ${{ secrets.SCCM_SLACK_TOKEN }}
